### ISSUE TITLE
Lagging

### ISSUE THREAD

**Issue by FlorentAnders** [tvbarthel/SimpleWeatherForecast#6]
On my Nexus 5, after having built the app, switching a day really lags. Is that normal? It doesn't lag on the play store version

**Comment by vbarthel-fr** [comment]
Hum, I have a Nexus 5 with the stock Android 4.4.4 and I don't have any lags, so hard to say :x

Do you notice any strange logs with logcat ? You could also try to disable the PageTransformer and the OnPageChangeListener and see if there is less lags.

https://github.com/tvbarthel/SimpleWeatherForecast/blob/master/SimpleWeatherForecast/src/main/java/fr/tvbarthel/apps/simpleweatherforcast/MainActivity.java#L266

https://github.com/tvbarthel/SimpleWeatherForecast/blob/master/SimpleWeatherForecast/src/main/java/fr/tvbarthel/apps/simpleweatherforcast/MainActivity.java#L268

I will try to investigate this issue as soon as I have a little more free times !

**Comment by FlorentAnders** [comment]
Fixed it

**Comment by vbarthel-fr** [comment]
Nice ! Could you give me more details about what you did to fix it ?

I forgot to thank you for your contribution to this small project, I really appreciate that you took the time to write an issue! Thanks a lot =)

**Comment by FlorentAnders** [comment]
I'm so sorry to say I don't exactly know what it was, I just re-copied the project :/

You've done an amazing work here, my pleasure :)

**Comment by vbarthel-fr** [comment]
No problem! I'm glad that the application works as intended now =) Don't hesitate if you have any other questions about this project.

Happy coding!

**Comment by vbarthel-fr** [comment]
getWindow.setBackground() seems to be the reason of the lag.

**Comment by vbarthel-fr** [comment]
377cec833320136c53d6ff0151126f74e7ea2031
